import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
test('Paquete GAS comparte fuente de dominio exacta y compila sin módulos', () => {
  const domain = readFileSync(new URL('../app/src/model/clinical-record.js', import.meta.url), 'utf8');
  const gateway = readFileSync(new URL('../api/gateway.js', import.meta.url), 'utf8');
  const generated = readFileSync(new URL('../api/generated/domain.gs', import.meta.url), 'utf8');
  const expected = '// GENERATED by npm run build:api. Do not edit.\n' + [domain, gateway].map(source => source.replace(/^import .*;\r?\n/gm, '').replace(/^export /gm, '')).join('\n');
  assert.equal(generated.replaceAll('\r\n', '\n'), expected.replaceAll('\r\n', '\n'));
  const adapter = readFileSync(new URL('../api/apps-script/adapter.gs', import.meta.url), 'utf8');
  const smoke = readFileSync(new URL('../api/apps-script/smoke.gs', import.meta.url), 'utf8');
  const context = vm.createContext({});
  vm.runInContext([generated, adapter, smoke].join('\n'), context);
  assert.equal(typeof context.initializeNextTest, 'function');
  assert.equal(typeof context.runNextTestSmoke, 'function');
  assert.equal(typeof context.doPost, 'function');
});
