import { readFile, writeFile, mkdir } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const domain = await readFile(new URL('app/src/model/clinical-record.js', root), 'utf8');
const gateway = await readFile(new URL('api/gateway.js', root), 'utf8');
const output = '// GENERATED by npm run build:api. Do not edit.\n' + [domain, gateway].map(source => source.replace(/^import .*;\r?\n/gm, '').replace(/^export /gm, '')).join('\n');
await mkdir(new URL('api/generated/', root), { recursive: true });
await writeFile(new URL('api/generated/domain.gs', root), output);
console.log('API TEST generada desde el mismo dominio que usa la PWA.');
